### ISSUE TITLE
Update GraphiQL

### ISSUE THREAD

**Issue by zerolab** [torchbox/wagtail-grapple#104]
as per 
https://github.com/graphql-python/graphene-django/releases/tag/v2.12.0
https://github.com/graphql-python/graphene-django/releases/tag/v2.12.1
https://github.com/graphql-python/graphene-django/releases/tag/v2.13.0

This should also simplify the subscriptions logic a bit

**Comment by dopry** [comment]
we are currently on graphiql 2.0.13. there have been a few releases since... 

https://github.com/graphql/graphiql/releases/tag/graphiql%402.1.0
https://github.com/graphql/graphiql/releases/tag/graphiql%402.2.0
https://github.com/graphql/graphiql/releases/tag/graphiql%402.4.0
https://github.com/graphql/graphiql/releases/tag/graphiql%402.4.1

We should figure out a way to have dependabot or some other service notify us of graphiql updates.
