### ISSUE TITLE
Add django 4.1 support

### ISSUE THREAD

**Issue by Khatskevich** [torchbox/wagtail-grapple#241]
Wagtail now supports Django 4.1.
For some users wagtail-grapple may be the last dependency which prevents from updating Django.

It will be nice to have support Django 4.1.

**Comment by jams2** [comment]
This appears to be due to `graphene-django` being incompatible with Django 4 (4.1?).

`graphene-django` [appears to be unmaintained](https://github.com/graphql-python/graphene-django/issues/1334). See also https://github.com/graphql-python/graphene-django/issues/1324#issuecomment-1140494403.

This will probably also affect https://github.com/torchbox/wagtail-grapple/pull/143

**Comment by PeterDekkers** [comment]
`graphene-django` v3.0.0 was just released, which adds Django 4 support.

https://github.com/graphql-python/graphene-django/releases/tag/v3.0.0

**Comment by zerolab** [comment]
cross-posted to #143.
